Repository BagasKelana/E-Commerce-Colab, pull requests merged in 2024-01, with the labels that each got.

#31 Feature/product-detail
  public/images/713kdrCldgL._AC_SY450_.jpg
  src/RoutesApp.tsx
  src/fetchUser.d.ts
  src/index.css
  src/pages/ProductDetailsPage.tsx
Labels: enhancement

#33 Fix/DashboardPage & LandingPage
  src/ProductCategories.tsx
  src/RoutesApp.tsx
  src/components/Card/ProductCard.tsx
  src/components/Card/SkeletonCategoryCard.tsx
  src/components/DataLoader.tsx
  src/components/EmptyData.tsx
  src/components/ErrorBoundary.tsx
  src/components/Navbar.tsx
  src/components/dashboard-page/Products/ProductsAdmin.tsx
  src/components/dashboard-page/Products/table/DataTable.tsx
  src/components/dashboard-page/Products/table/FilterProductCategory.tsx
  src/components/dashboard-page/Products/table/FilterProductTable.tsx
  src/components/dashboard-page/Products/table/table-column-def-func.tsx
  src/components/dashboard-page/Products/update-product/CategoriesBox.tsx
  src/components/dashboard-page/Products/update-product/ToggleBox.tsx
  src/components/dashboard-page/Products/update-product/UpdateProduct.tsx
  src/components/dashboard-page/table-component/DataTableColumnHeader.tsx
  src/components/landing-page/FeaturedProducts.tsx
  src/components/landing-page/PopulerCategories.tsx
  src/components/navbar/UserMenu.tsx
  src/components/ui/badge.tsx
  src/components/ui/input.tsx
  src/components/ui/spinner.tsx
  src/components/ui/table.tsx
  src/hook/useFetch.ts
  src/hook/useFetchDataTable.ts
  src/hook/useNavScroll.ts
  src/hook/useSearchProduct.ts
  src/pages/DashboardPage.tsx
  src/pages/LandingPage.tsx
  src/pages/ProductDetailsPage.tsx
  tailwind.config.js
Labels: enhancement

#34 fix/ bug fetching data
  .env.exsample
  src/ProductCategories.tsx
  src/components/Navbar.tsx
  src/components/dashboard-page/Category/CategoryManagement.tsx
  src/components/dashboard-page/Category/table/table-column-def-func.tsx
  src/components/dashboard-page/Products/ProductsAdmin.tsx
  src/components/dashboard-page/Products/table/table-column-def-func.tsx
  src/components/dashboard-page/User/UserManagement.tsx
  src/components/dashboard-page/User/table/table-column-def-func.tsx
  src/components/landing-page/FeaturedProducts.tsx
  src/components/navbar/HumburgerMenu.tsx
  src/components/user-page/UserChangePasswordForm.tsx
  src/components/user-page/UserProfileForm.tsx
  src/helpers/showImageAPI.ts
  src/hook/useDataTable.ts
  src/hook/useFetch.ts
  src/hook/useFetchDataTable.ts
  src/hook/useSearchProduct.ts
  src/lib/delete-item-func.ts
  src/pages/ProductDetailsPage.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  vite.config.ts
Labels: bug

#35 fix: dashboard admin
  src/components/dashboard-page/Category/AddCategory.tsx
  src/components/dashboard-page/Products/add-product/AddProduct.tsx
  src/components/dashboard-page/table-component/DataTabelPagination.tsx
  src/components/ui/button.tsx
  src/hook/useFetchDataTable.ts
Labels: enhancement

#36 fix/user-profile
  src/components/Card/ProductCard.tsx
  src/components/Navbar.tsx
  src/components/navbar/UserMenu.tsx
  src/components/ui/input.tsx
  src/components/user-page/UserProfileForm.tsx
  src/components/user-page/order-detail/UserOrderDetail.tsx
  src/pages/LandingPage.tsx
Labels: bug

#37 Dev branch
  .env.exsample
  public/images/713kdrCldgL._AC_SY450_.jpg
  src/ProductCategories.tsx
  src/RoutesApp.tsx
  src/components/Card/ProductCard.tsx
  src/components/Card/SkeletonCategoryCard.tsx
  src/components/DataLoader.tsx
  src/components/EmptyData.tsx
  src/components/ErrorBoundary.tsx
  src/components/Navbar.tsx
  src/components/dashboard-page/Category/AddCategory.tsx
  src/components/dashboard-page/Category/CategoryManagement.tsx
  src/components/dashboard-page/Category/table/table-column-def-func.tsx
  src/components/dashboard-page/Products/ProductsAdmin.tsx
  src/components/dashboard-page/Products/add-product/AddProduct.tsx
  src/components/dashboard-page/Products/table/DataTable.tsx
  src/components/dashboard-page/Products/table/FilterProductCategory.tsx
  src/components/dashboard-page/Products/table/FilterProductTable.tsx
  src/components/dashboard-page/Products/table/table-column-def-func.tsx
  src/components/dashboard-page/Products/update-product/CategoriesBox.tsx
  src/components/dashboard-page/Products/update-product/ToggleBox.tsx
  src/components/dashboard-page/Products/update-product/UpdateProduct.tsx
  src/components/dashboard-page/User/UserManagement.tsx
  src/components/dashboard-page/User/table/table-column-def-func.tsx
  src/components/dashboard-page/table-component/DataTabelPagination.tsx
  src/components/dashboard-page/table-component/DataTableColumnHeader.tsx
  src/components/landing-page/FeaturedProducts.tsx
  src/components/landing-page/PopulerCategories.tsx
  src/components/navbar/HumburgerMenu.tsx
  src/components/navbar/UserMenu.tsx
  src/components/ui/badge.tsx
  src/components/ui/button.tsx
  src/components/ui/input.tsx
  src/components/ui/spinner.tsx
  src/components/ui/table.tsx
  src/components/user-page/UserChangePasswordForm.tsx
  src/components/user-page/UserProfileForm.tsx
  src/components/user-page/order-detail/UserOrderDetail.tsx
  src/fetchUser.d.ts
  src/helpers/showImageAPI.ts
  src/hook/useDataTable.ts
  src/hook/useFetch.ts
  src/hook/useFetchDataTable.ts
  src/hook/useNavScroll.ts
  src/hook/useSearchProduct.ts
  src/index.css
  src/lib/delete-item-func.ts
  src/pages/DashboardPage.tsx
  src/pages/LandingPage.tsx
  src/pages/ProductDetailsPage.tsx
  src/pages/SignIn.tsx
  src/pages/SignUp.tsx
  tailwind.config.js
  vite.config.ts
Labels: bug, enhancement

#39 refactor: home page
  .eslintrc.cjs
  .eslintrc.json
  .gitignore
  .prettierrc
  .vscode/settings.json
  package-lock.json
  package.json
  src/App.tsx
  src/RoutesApp.tsx
  src/components/EmptyData.tsx
  src/components/EmptyData/index.tsx
  src/components/ErrorBoundary.tsx
  src/components/ErrorBoundary/index.tsx
  src/components/Footer.tsx
  src/components/Footer/index.tsx
  src/components/PrivateRoute/UserPrivateRoute.tsx
  src/components/dashboard-page/Products/add-product/AddProduct.tsx
  src/components/landing-page/FeaturedProducts.tsx
  src/components/landing-page/LandingHero.tsx
  src/components/landing-page/PopulerCategories.tsx
  src/components/landing-page/landing-page.css
  src/components/user-page/UserOrder.tsx
  src/constants/path.ts
  src/constants/url.ts
  src/helpers/httpService.ts
  src/helpers/showImageAPI.ts
  src/hook/useFetch.ts
  src/layout/Layout.tsx
  src/main.tsx
  src/modules/category/hooks/useCategory.ts
  src/modules/category/modules/category.ts
  src/modules/category/services/index.ts
  src/pages/Admin/Dashboard/index.tsx
  src/pages/Cart/Cart.tsx
  src/pages/Cart/columns.tsx
  src/pages/Cart/index.tsx
  src/pages/DashboardPage.tsx
  src/pages/Home/components/FeaturedProducts/index.tsx
  src/pages/Home/components/GamingSetup/index.tsx
  src/pages/Home/components/LandingHero/index.tsx
  src/pages/Home/components/LandingHero/landing-page.css
  src/pages/Home/components/PopulerCategories/index.tsx
  src/pages/Home/index.tsx
  src/pages/LandingPage.tsx
  src/pages/Product/index.tsx
  src/pages/ProductDetail/index.tsx
  src/pages/ProductDetailsPage.tsx
  src/pages/ProductPage.tsx
  src/pages/SignIn.tsx
  src/pages/SignIn/index.tsx
  src/pages/SignUp.tsx
  src/pages/SignUp/index.tsx
  src/pages/User.tsx
  src/pages/User/index.tsx
  src/pages/UserChangePassword/components/UserChangePasswordForm/index.tsx
  src/pages/UserChangePassword/components/UserProfileDescription/index.tsx
  src/pages/UserChangePassword/index.tsx
  src/pages/UserOrder/components/OrderCart/index.tsx
  src/pages/UserOrder/index.tsx
  src/types/HttpResponse.d.ts
Labels: Ready To Review
